# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'



target 'over-counter-app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for over-counter-app

  target 'over-counter-app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'over-counter-appTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'over-counter-app-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for over-counter-app-tvOS

  target 'over-counter-app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
